export const SET_LINE_PRODUCTS_MEDIUM_LIST = "SET_LINE_PRODUCTS_MEDIUM_LIST";
export const SET_LINE_PRODUCTS_SMALL_LIST = "SET_LINE_PRODUCTS_SMALL_LIST";
export const SET_PRODUCTS_LIST = "SET_PRODUCTS_LIST";
export const SET_CATALOGS_LIST = "SET_CATALOGS_LIST";
